package builder

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Generate writes the statically wired runtime main package into a restored
// root module.
func Generate(rootDirectory string, lock *Lock, graph *Graph) error {
	aliasByPath := map[string]string{
		lock.SDK.ModulePath:             "sdk",
		lock.SDK.ModulePath + "/config": "sdkconfig",
	}
	mainImports := map[string]string{
		"context": "context", "errors": "errors", "fmt": "fmt", "os": "os", "os/signal": "signal",
		"path/filepath": "filepath", "reflect": "reflect", "strings": "strings", "sync": "sync", "time": "time",
		lock.SDK.ModulePath: "sdk", lock.SDK.ModulePath + "/application": "sdkapplication",
	}
	wiringImports := map[string]string{
		"context": "context", "fmt": "fmt", "os": "os", "path/filepath": "filepath", "reflect": "reflect",
		lock.SDK.ModulePath: "sdk", lock.SDK.ModulePath + "/application": "sdkapplication", lock.SDK.ModulePath + "/config": "sdkconfig",
	}
	hasDependencies := false
	for _, component := range graph.Components {
		hasDependencies = hasDependencies || len(component.DependencyList) > 0
	}
	if !hasDependencies {
		delete(wiringImports, "reflect")
	}
	paths := []string{}
	for _, component := range graph.Components {
		paths = append(paths, component.ImportPath, component.ConfigImport)
		for _, dependency := range component.DependencyList {
			// ONE assignments never spell the capability type: the composite
			// literal field is assigned directly from a provider export. Only
			// OPTIONAL (sdk.None/sdk.Some type argument) and MANY (slice type)
			// expressions reference the target package, so only those imports
			// are collected. Importing an unreferenced package breaks the
			// generated build.
			if dependency.Cardinality == CardinalityOne {
				continue
			}
			_ = types.TypeString(dependency.Target, func(pkg *types.Package) string {
				paths = append(paths, pkg.Path())
				return pkg.Name()
			})
		}
	}
	paths = uniqueStrings(paths)
	sort.Strings(paths)
	for i, importPath := range paths {
		if _, exists := wiringImports[importPath]; !exists {
			alias := fmt.Sprintf("pluginpkg%d", i)
			wiringImports[importPath], aliasByPath[importPath] = alias, alias
		}
	}

	var mainSource, wiringSource bytes.Buffer
	writeGeneratedHeader(&mainSource, mainImports)
	writeGeneratedHeader(&wiringSource, wiringImports)
	writeRuntimeSupport(&mainSource, lock.SDK.ModulePath)
	writeRuntimeConfig(&wiringSource, lock, aliasByPath)
	writeWiring(&wiringSource, lock, graph, aliasByPath)
	if err := formatAndWriteGenerated(rootDirectory, "main.go", mainSource.Bytes()); err != nil {
		return err
	}
	if err := formatAndWriteGenerated(rootDirectory, "wiring_gen.go", wiringSource.Bytes()); err != nil {
		return err
	}
	if err := formatAndWriteGenerated(rootDirectory, "signals_nonwindows_gen.go", []byte("//go:build !windows\n\npackage main\n\nimport (\n\t\"os\"\n\t\"syscall\"\n)\n\nfunc processSignals() []os.Signal { return []os.Signal{os.Interrupt, syscall.SIGTERM} }\n")); err != nil {
		return err
	}
	return formatAndWriteGenerated(rootDirectory, "signals_windows_gen.go", []byte("//go:build windows\n\npackage main\n\nimport \"os\"\n\nfunc processSignals() []os.Signal { return []os.Signal{os.Interrupt} }\n"))
}

func writeGeneratedHeader(source *bytes.Buffer, imports map[string]string) {
	source.WriteString("// Code generated by ingot Builder. DO NOT EDIT.\npackage main\n\nimport (\n")
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		_, _ = fmt.Fprintf(source, "\t%s %q\n", imports[path], path)
	}
	source.WriteString(")\n\n")
}

func formatAndWriteGenerated(rootDirectory, name string, source []byte) error {
	formatted, err := format.Source(source)
	if err != nil {
		invalidPath := filepath.Join(rootDirectory, strings.TrimSuffix(name, ".go")+"_invalid.go")
		_ = os.WriteFile(invalidPath, source, 0o644)
		return &Error{Code: "INGOT-CODEGEN", Path: invalidPath, Err: err}
	}
	return os.WriteFile(filepath.Join(rootDirectory, name), formatted, 0o644)
}

func writeRuntimeSupport(source *bytes.Buffer, sdkModule string) {
	_, _ = fmt.Fprintf(source, "const ingotSDKModule = %q\n\n", sdkModule)
	source.WriteString(`
const defaultCleanupTimeout = 10 * time.Second

type processControl struct {
	arguments []string
	check bool
	cancel context.CancelFunc
	once sync.Once
	mu sync.Mutex
	requested bool
	err error
}

func newProcessControl(arguments []string, check bool, cancel context.CancelFunc) *processControl {
	return &processControl{arguments: append([]string(nil), arguments...), check: check, cancel: cancel}
}

func (p *processControl) Arguments() []string {
	return append([]string(nil), p.arguments...)
}

func (p *processControl) Check() bool { return p.check }

func (p *processControl) Shutdown(err error) {
	p.once.Do(func() {
		p.mu.Lock()
		p.requested = true
		p.err = err
		p.mu.Unlock()
		p.cancel()
	})
}

func (p *processControl) result() (bool, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.requested, p.err
}

var _ sdkapplication.Process = (*processControl)(nil)

func validateRequired(value reflect.Value, path string) error {
	if !value.IsValid() {
		return fmt.Errorf("%s: invalid capability value", path)
	}
	for value.Kind() == reflect.Interface {
		if value.IsNil() {
			return fmt.Errorf("%s: nil capability value", path)
		}
		value = value.Elem()
	}
	typeValue := value.Type()
	if typeValue.PkgPath() == ingotSDKModule && strings.HasPrefix(typeValue.Name(), "Optional[") {
		if !value.FieldByName("Valid").Bool() {
			return nil
		}
		return validateRequired(value.FieldByName("Value"), path+".Value")
	}
	if typeValue.PkgPath() == ingotSDKModule && strings.HasPrefix(typeValue.Name(), "Named[") {
		name := value.FieldByName("Name").String()
		if name == "" {
			return fmt.Errorf("%s.Name: empty capability name", path)
		}
		return validateRequired(value.FieldByName("Value"), path+"["+name+"].Value")
	}
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.Slice:
		if value.IsNil() {
			return fmt.Errorf("%s: nil capability value", path)
		}
	}
	if value.Kind() == reflect.Slice {
		return validateCollection(value, path, false)
	}
	return nil
}

func namedIdentity(value reflect.Value) (string, bool) {
	for value.IsValid() && value.Kind() == reflect.Interface {
		if value.IsNil() { return "", false }
		value = value.Elem()
	}
	if !value.IsValid() { return "", false }
	typeValue := value.Type()
	if typeValue.PkgPath() == ingotSDKModule && strings.HasPrefix(typeValue.Name(), "Optional[") {
		if !value.FieldByName("Valid").Bool() { return "", false }
		return namedIdentity(value.FieldByName("Value"))
	}
	if typeValue.PkgPath() == ingotSDKModule && strings.HasPrefix(typeValue.Name(), "Named[") {
		return value.FieldByName("Name").String(), true
	}
	return "", false
}

func validateCollection(value reflect.Value, path string, outerMany bool) error {
	if value.IsNil() && !outerMany {
		return fmt.Errorf("%s: nil capability collection", path)
	}
	seenNames := map[string]int{}
	for index := 0; index < value.Len(); index++ {
		item := value.Index(index)
		if name, ok := namedIdentity(item); ok {
			if previous, duplicate := seenNames[name]; duplicate {
				return fmt.Errorf("%s[%d]: duplicate capability name %q (first at index %d)", path, index, name, previous)
			}
			seenNames[name] = index
		}
		if err := validateRequired(item, fmt.Sprintf("%s[%d]", path, index)); err != nil { return err }
	}
	return nil
}

func cleanupAll(parent context.Context, cleanups []sdk.Cleanup, cause error) error {
	errorsFound := []error{}
	if cause != nil { errorsFound = append(errorsFound, cause) }
	base := context.WithoutCancel(parent)
	for index := len(cleanups)-1; index >= 0; index-- {
		cleanupContext, cancel := context.WithTimeout(base, defaultCleanupTimeout)
		err := cleanups[index](cleanupContext)
		deadlineErr := cleanupContext.Err()
		cancel()
		if err != nil { errorsFound = append(errorsFound, err) }
		if deadlineErr != nil { errorsFound = append(errorsFound, deadlineErr) }
	}
	return errors.Join(errorsFound...)
}

func main() {
	check := false
	for index, argument := range os.Args[1:] {
		if argument == "--ingot-check" {
			if check || len(os.Args) != 2 {
				_, _ = fmt.Fprintln(os.Stderr, "--ingot-check must be the only runtime argument")
				os.Exit(2)
			}
			check = true
			continue
		}
		if strings.HasPrefix(argument, "--ingot-") {
			_, _ = fmt.Fprintf(os.Stderr, "unknown ingot runtime argument at index %d: %s\n", index, argument)
			os.Exit(2)
		}
	}
	home := os.Getenv("INGOT_HOME")
	if home == "" {
		userHome, err := os.UserHomeDir()
		if err != nil { _, _ = fmt.Fprintln(os.Stderr, err); os.Exit(1) }
		home = filepath.Join(userHome, ".ingot")
	}
	configPath := os.Getenv("INGOT_CONFIG")
	if configPath == "" { configPath = filepath.Join(home, "config.toml") }
	stateRoot := os.Getenv("INGOT_STATE_ROOT")
	if stateRoot == "" { stateRoot = filepath.Join(home, "state") }
	processContext, stop := signal.NotifyContext(context.Background(), processSignals()...)
	defer stop()
	runtimeContext, cancelRuntime := context.WithCancel(processContext)
	defer cancelRuntime()
	arguments := append([]string(nil), os.Args[1:]...)
	if check { arguments = nil }
	process := newProcessControl(arguments, check, cancelRuntime)
	if err := run(runtimeContext, configPath, stateRoot, check, process); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

`)
}

func writeRuntimeConfig(source *bytes.Buffer, lock *Lock, aliases map[string]string) {
	source.WriteString("type decodedConfigs struct {\n")
	for i, plugin := range lock.Plugins {
		_, _ = fmt.Fprintf(source, "\tPlugin%d %s.Config\n", i, aliases[joinImport(plugin.ID, plugin.RootPackage)])
	}
	source.WriteString("}\n\nfunc decodeConfigs(path string) (decodedConfigs, error) {\n\tvar result decodedConfigs\n\tdata, err := os.ReadFile(path)\n\tif err != nil { return result, fmt.Errorf(\"read runtime config: %w\", err) }\n\ttables, err := sdkconfig.ResolveTables(data, []sdkconfig.PluginReference{\n")
	for _, plugin := range lock.Plugins {
		_, _ = fmt.Fprintf(source, "\t\t{ID: %q, Name: %q},\n", plugin.ID, plugin.Name)
	}
	source.WriteString("\t})\n\tif err != nil { return result, err }\n")
	for i, plugin := range lock.Plugins {
		_, _ = fmt.Fprintf(source, "\tresult.Plugin%d, err = sdkconfig.Decode[%s.Config](tables[%q])\n\tif err != nil { return result, fmt.Errorf(%q, err) }\n", i, aliases[joinImport(plugin.ID, plugin.RootPackage)], plugin.ID, "decode config for plugin "+plugin.ID+": %w")
	}
	source.WriteString("\treturn result, nil\n}\n\n")
}

func writeWiring(source *bytes.Buffer, lock *Lock, graph *Graph, aliases map[string]string) {
	componentNumber := map[*Component]int{}
	for i, component := range graph.Components {
		componentNumber[component] = i
	}
	pluginNumber := map[string]int{}
	for i, plugin := range lock.Plugins {
		pluginNumber[plugin.ID] = i
	}
	source.WriteString("func run(ctx context.Context, configPath, stateRoot string, check bool, process *processControl) error {\n\tctx = sdkapplication.WithProcess(ctx, process)\n\tconfigs, err := decodeConfigs(configPath)\n\tif err != nil { return err }\n\tcleanups := []sdk.Cleanup{}\n")
	for _, component := range graph.CreationOrder {
		number := componentNumber[component]
		alias := aliases[component.ImportPath]
		_, _ = fmt.Fprintf(source, "\tcomponentContext%d := sdkconfig.WithStateDir(ctx, filepath.Join(stateRoot, %q))\n", number, component.PluginID)
		_, _ = fmt.Fprintf(source, "\tif err := os.MkdirAll(filepath.Join(stateRoot, %q), 0o700); err != nil { return cleanupAll(ctx, cleanups, err) }\n", component.PluginID)
		_, _ = fmt.Fprintf(source, "\tdeps%d := %s.Dependencies{\n", number, alias)
		for _, dependency := range component.DependencyList {
			_, _ = fmt.Fprintf(source, "\t\t%s: %s,\n", dependency.Name, dependencyExpression(dependency, componentNumber, aliases))
		}
		source.WriteString("\t}\n")
		for _, dependency := range component.DependencyList {
			path := component.ID + ".Dependencies." + dependency.Name
			if dependency.Cardinality == CardinalityMany {
				_, _ = fmt.Fprintf(source, "\tif err := validateCollection(reflect.ValueOf(deps%d.%s), %q, true); err != nil { return cleanupAll(ctx, cleanups, err) }\n", number, dependency.Name, path)
			} else {
				_, _ = fmt.Fprintf(source, "\tif err := validateRequired(reflect.ValueOf(deps%d.%s), %q); err != nil { return cleanupAll(ctx, cleanups, err) }\n", number, dependency.Name, path)
			}
		}
		_, _ = fmt.Fprintf(source, "\texports%d, cleanup, constructErr := %s.New(componentContext%d, configs.Plugin%d, deps%d)\n", number, alias, number, pluginNumber[component.PluginID], number)
		_, _ = fmt.Fprintf(source, "\t_ = exports%d\n", number)
		source.WriteString("\tif cleanup != nil { cleanups = append(cleanups, cleanup) }\n")
		_, _ = fmt.Fprintf(source, "\tif constructErr != nil { return cleanupAll(ctx, cleanups, fmt.Errorf(%q, constructErr)) }\n", "construct "+component.ID+": %w")
	}
	source.WriteString("\tif check { return cleanupAll(ctx, cleanups, nil) }\n\t<-ctx.Done()\n\t_, shutdownErr := process.result()\n\treturn cleanupAll(ctx, cleanups, shutdownErr)\n}\n")
}

func dependencyExpression(dependency *Dependency, componentNumber map[*Component]int, aliases map[string]string) string {
	typeString := func(value types.Type) string {
		return types.TypeString(value, func(pkg *types.Package) string {
			if alias, ok := aliases[pkg.Path()]; ok {
				return alias
			}
			return pkg.Name()
		})
	}
	sourceExpression := func(provider Provider) string {
		return fmt.Sprintf("exports%d.%s", componentNumber[provider.Component], provider.Export.Name)
	}
	switch dependency.Cardinality {
	case CardinalityOne:
		return sourceExpression(dependency.Providers[0])
	case CardinalityOptional:
		if len(dependency.Providers) == 0 {
			return fmt.Sprintf("sdk.None[%s]()", typeString(dependency.Target))
		}
		return fmt.Sprintf("sdk.Some[%s](%s)", typeString(dependency.Target), sourceExpression(dependency.Providers[0]))
	case CardinalityMany:
		var expression strings.Builder
		target := typeString(dependency.Target)
		_, _ = fmt.Fprintf(&expression, "func() []%s { values := make([]%s, 0)", target, target)
		for _, provider := range dependency.Providers {
			suffix := ""
			if provider.Flatten {
				suffix = "..."
			}
			_, _ = fmt.Fprintf(&expression, "; values = append(values, %s%s)", sourceExpression(provider), suffix)
		}
		expression.WriteString("; return values }()")
		return expression.String()
	default:
		panic("unknown cardinality " + dependency.Cardinality)
	}
}

func quote(value string) string { return strconv.Quote(value) }
