package builder

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Generate writes the statically wired runtime main package into a restored
// root module.
func Generate(rootDirectory string, lock *Lock, graph *Graph) error {
	aliasByPath := map[string]string{}
	mainImports := map[string]string{
		"context": "context", "errors": "errors", "fmt": "fmt", "os": "os", "os/signal": "signal",
		"path/filepath": "filepath", "reflect": "reflect", "strings": "strings", "sync": "sync", "time": "time",
		IngotABIModulePath:                 "ingotabi",
		IngotABIModulePath + "/invocation": "invocation",
		IngotABIModulePath + "/lifecycle":  "lifecycle",
		IngotABIModulePath + "/state":      "state",
	}
	wiringImports := map[string]string{
		"context": "context", "bytes": "bytes", "errors": "errors", "fmt": "fmt", "os": "os", "path/filepath": "filepath", "reflect": "reflect",
		IngotABIModulePath:                 "ingotabi",
		IngotABIModulePath + "/invocation": "invocation",
		RuntimeSupportTOMLModule:           "toml",
	}
	aliasByPath[IngotABIModulePath] = "ingotabi"
	hasValidate := false
	hasState := false
	for _, component := range graph.Components {
		for _, dependency := range component.DependencyList {
			if !dependency.Host {
				hasValidate = true
			}
			if dependency.Host && dependency.HostType == "state" {
				hasState = true
			}
		}
	}
	if !hasValidate {
		delete(wiringImports, "reflect")
	}
	if !hasState {
		delete(wiringImports, "path/filepath")
	}
	paths := []string{}
	for _, component := range graph.Components {
		paths = append(paths, component.ImportPath, component.ConfigImport)
		for _, dependency := range component.DependencyList {
			if dependency.WrapperRuntime != "" {
				wiringImports[dependency.WrapperRuntime] = aliasByPath[dependency.WrapperRuntime]
			}
			// ONE assignments never spell the capability type: the composite
			// literal field is assigned directly from a provider export. Only
			// OPTIONAL (ingotabi.None/ingotabi.Some type argument) and
			// MANY (slice type) expressions reference the target package, so
			// only those imports are collected. Importing an unreferenced
			// package breaks the generated build.
			if dependency.Cardinality == CardinalityOne || dependency.Host {
				continue
			}
			_ = types.TypeString(dependency.Target, func(pkg *types.Package) string {
				paths = append(paths, pkg.Path())
				return pkg.Name()
			})
		}
	}
	paths = uniqueStrings(paths)
	sort.Strings(paths)
	for i, importPath := range paths {
		if _, exists := wiringImports[importPath]; !exists {
			alias := fmt.Sprintf("pluginpkg%d", i)
			wiringImports[importPath], aliasByPath[importPath] = alias, alias
		}
	}

	var mainSource, wiringSource bytes.Buffer
	writeGeneratedHeader(&mainSource, mainImports)
	writeGeneratedHeader(&wiringSource, wiringImports)
	writeRuntimeSupport(&mainSource)
	writeRuntimeConfig(&wiringSource, lock, aliasByPath)
	writeWiring(&wiringSource, lock, graph, aliasByPath)
	if err := formatAndWriteGenerated(rootDirectory, "main.go", mainSource.Bytes()); err != nil {
		return err
	}
	if err := formatAndWriteGenerated(rootDirectory, "wiring_gen.go", wiringSource.Bytes()); err != nil {
		return err
	}
	buildTags := fmt.Sprintf(`//go:build !windows

package main

import (
	"os"
	"syscall"
)

func processSignals() []os.Signal { return []os.Signal{os.Interrupt, syscall.SIGTERM} }
`)
	if err := formatAndWriteGenerated(rootDirectory, "signals_nonwindows_gen.go", []byte(buildTags)); err != nil {
		return err
	}
	return formatAndWriteGenerated(rootDirectory, "signals_windows_gen.go", []byte("//go:build windows\n\npackage main\n\nimport \"os\"\n\nfunc processSignals() []os.Signal { return []os.Signal{os.Interrupt} }\n"))
}

func writeGeneratedHeader(source *bytes.Buffer, imports map[string]string) {
	source.WriteString("// Code generated by ingot Builder. DO NOT EDIT.\npackage main\n\nimport (\n")
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		_, _ = fmt.Fprintf(source, "\t%s %q\n", imports[path], path)
	}
	source.WriteString(")\n\n")
}

func formatAndWriteGenerated(rootDirectory, name string, source []byte) error {
	formatted, err := format.Source(source)
	if err != nil {
		invalidPath := filepath.Join(rootDirectory, strings.TrimSuffix(name, ".go")+"_invalid.go")
		_ = os.WriteFile(invalidPath, source, 0o644)
		return &Error{Code: "INGOT-CODEGEN", Path: invalidPath, Err: err}
	}
	return os.WriteFile(filepath.Join(rootDirectory, name), formatted, 0o644)
}

func writeRuntimeSupport(source *bytes.Buffer) {
	source.WriteString("var ingotRuntimeModules = map[string]struct{}{\n")
	_, _ = fmt.Fprintf(source, "\t%q: {},\n", IngotABIModulePath)
	source.WriteString("}\n\n")
	source.WriteString(`
const defaultCleanupTimeout = 10 * time.Second

// processControl is the generated runtime implementation of the host
// contracts: invocation.Invocation, lifecycle.Controller and, indirectly,
// the state.Scope values assigned per Component.
type processControl struct {
	arguments []string
	mode      invocation.Mode
	cancel    context.CancelFunc
	mu        sync.Mutex
	requested bool
	causes    []error
}

func newProcessControl(arguments []string, mode invocation.Mode, cancel context.CancelFunc) *processControl {
	return &processControl{arguments: append([]string(nil), arguments...), mode: mode, cancel: cancel}
}

func (p *processControl) Arguments() []string {
	return append([]string(nil), p.arguments...)
}

func (p *processControl) Mode() invocation.Mode { return p.mode }

// RequestShutdown is concurrent-safe and non-blocking. The first request
// cancels the runtime context; every non-nil cause is aggregated so a later
// fatal error can never be hidden by an earlier normal-completion request.
func (p *processControl) RequestShutdown(err error) {
	first := false
	p.mu.Lock()
	if !p.requested {
		p.requested = true
		first = true
	}
	if err != nil {
		p.causes = append(p.causes, err)
	}
	p.mu.Unlock()
	if first {
		p.cancel()
	}
}

func (p *processControl) result() error {
	p.mu.Lock()
	defer p.mu.Unlock()
	return errors.Join(p.causes...)
}

var _ lifecycle.Controller = (*processControl)(nil)
var _ invocation.Invocation = (*processControl)(nil)

// stateScope is the generated runtime assignment of one Component's
// Plugin-scoped persistent state directory. It carries only the location;
// file access and persistence remain the Plugin's responsibility.
type stateScope struct{ dir string }

func (s stateScope) Dir() string { return s.dir }

var _ state.Scope = stateScope{}

func validateRequired(value reflect.Value, path string) error {
	if !value.IsValid() {
		return fmt.Errorf("%s: invalid capability value", path)
	}
	for value.Kind() == reflect.Interface {
		if value.IsNil() {
			return fmt.Errorf("%s: nil capability value", path)
		}
		value = value.Elem()
	}
	typeValue := value.Type()
	if _, isRuntime := ingotRuntimeModules[typeValue.PkgPath()]; isRuntime {
		if strings.HasPrefix(typeValue.Name(), "Optional[") {
			if !value.FieldByName("Valid").Bool() {
				return nil
			}
			return validateRequired(value.FieldByName("Value"), path+".Value")
		}
		if strings.HasPrefix(typeValue.Name(), "Named[") {
			name := value.FieldByName("Name").String()
			if name == "" {
				return fmt.Errorf("%s.Name: empty capability name", path)
			}
			return validateRequired(value.FieldByName("Value"), path+"["+name+"].Value")
		}
	}
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Map, reflect.Pointer, reflect.Slice:
		if value.IsNil() {
			return fmt.Errorf("%s: nil capability value", path)
		}
	}
	if value.Kind() == reflect.Slice {
		return validateCollection(value, path, false)
	}
	return nil
}

func namedIdentity(value reflect.Value) (string, bool) {
	for value.IsValid() && value.Kind() == reflect.Interface {
		if value.IsNil() { return "", false }
		value = value.Elem()
	}
	if !value.IsValid() { return "", false }
	typeValue := value.Type()
	if _, isRuntime := ingotRuntimeModules[typeValue.PkgPath()]; isRuntime {
		if strings.HasPrefix(typeValue.Name(), "Optional[") {
			if !value.FieldByName("Valid").Bool() { return "", false }
			return namedIdentity(value.FieldByName("Value"))
		}
		if strings.HasPrefix(typeValue.Name(), "Named[") {
			return value.FieldByName("Name").String(), true
		}
	}
	return "", false
}

func validateCollection(value reflect.Value, path string, outerMany bool) error {
	if value.IsNil() && !outerMany {
		return fmt.Errorf("%s: nil capability collection", path)
	}
	seenNames := map[string]int{}
	for index := 0; index < value.Len(); index++ {
		item := value.Index(index)
		if name, ok := namedIdentity(item); ok {
			if previous, duplicate := seenNames[name]; duplicate {
				return fmt.Errorf("%s[%d]: duplicate capability name %q (first at index %d)", path, index, name, previous)
			}
			seenNames[name] = index
		}
		if err := validateRequired(item, fmt.Sprintf("%s[%d]", path, index)); err != nil { return err }
	}
	return nil
}

func cleanupAll(parent context.Context, cleanups []ingotabi.Cleanup, cause error) error {
	errorsFound := []error{}
	if cause != nil { errorsFound = append(errorsFound, cause) }
	base := context.WithoutCancel(parent)
	for index := len(cleanups)-1; index >= 0; index-- {
		cleanupContext, cancel := context.WithTimeout(base, defaultCleanupTimeout)
		err := cleanups[index](cleanupContext)
		deadlineErr := cleanupContext.Err()
		cancel()
		if err != nil { errorsFound = append(errorsFound, err) }
		if deadlineErr != nil { errorsFound = append(errorsFound, deadlineErr) }
	}
	return errors.Join(errorsFound...)
}

func main() {
	check := false
	for index, argument := range os.Args[1:] {
		if argument == "--ingot-check" {
			if check || len(os.Args) != 2 {
				_, _ = fmt.Fprintln(os.Stderr, "--ingot-check must be the only runtime argument")
				os.Exit(2)
			}
			check = true
			continue
		}
		if strings.HasPrefix(argument, "--ingot-") {
			_, _ = fmt.Fprintf(os.Stderr, "unknown ingot runtime argument at index %d: %s\n", index, argument)
			os.Exit(2)
		}
	}
	home := os.Getenv("INGOT_HOME")
	if home == "" {
		userHome, err := os.UserHomeDir()
		if err != nil { _, _ = fmt.Fprintln(os.Stderr, err); os.Exit(1) }
		home = filepath.Join(userHome, ".ingot")
	}
	configPath := os.Getenv("INGOT_CONFIG")
	if configPath == "" { configPath = filepath.Join(home, "config.toml") }
	stateRoot := os.Getenv("INGOT_STATE_ROOT")
	if stateRoot == "" { stateRoot = filepath.Join(home, "state") }
	absoluteStateRoot, err := filepath.Abs(stateRoot)
	if err != nil { _, _ = fmt.Fprintln(os.Stderr, fmt.Errorf("resolve state root: %w", err)); os.Exit(1) }
	stateRoot = absoluteStateRoot
	processContext, stop := signal.NotifyContext(context.Background(), processSignals()...)
	defer stop()
	runtimeContext, cancelRuntime := context.WithCancel(processContext)
	defer cancelRuntime()
	arguments := append([]string(nil), os.Args[1:]...)
	mode := invocation.ModeRun
	if check {
		arguments = nil
		mode = invocation.ModeCheck
	}
	process := newProcessControl(arguments, mode, cancelRuntime)
	if err := run(runtimeContext, configPath, stateRoot, process); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

`)
}

func writeRuntimeConfig(source *bytes.Buffer, lock *Lock, aliases map[string]string) {
	source.WriteString("type decodedConfigs struct {\n")
	for i, plugin := range lock.Plugins {
		_, _ = fmt.Fprintf(source, "\tPlugin%d %s.Config\n", i, aliases[joinImport(plugin.ID, plugin.RootPackage)])
	}
	source.WriteString("}\n\nfunc decodeConfigs(path string) (decodedConfigs, error) {\n\tvar result decodedConfigs\n\tdata, err := os.ReadFile(path)\n\tif err != nil { return result, fmt.Errorf(\"read runtime config: %w\", err) }\n\tdecoder := toml.NewDecoder(bytes.NewReader(data))\n\tdecoder.DisallowUnknownFields()\n\tvar document struct {\n\t\tPlugins map[string]map[string]any `toml:\"plugins\"`\n\t}\n\tif err := decoder.Decode(&document); err != nil { return result, fmt.Errorf(\"parse runtime config: %w\", err) }\n")
	for i, plugin := range lock.Plugins {
		_, _ = fmt.Fprintf(source, "\ttable%d, err := resolveConfigTable(document.Plugins, %q, %q)\n", i, plugin.ID, plugin.Name)
		_, _ = fmt.Fprintf(source, "\tif err != nil { return result, fmt.Errorf(\"resolve config for plugin %s: %%w\", err) }\n", plugin.ID)
		_, _ = fmt.Fprintf(source, "\tresult.Plugin%d, err = strictDecodeConfig[%s.Config](table%d)\n", i, aliases[joinImport(plugin.ID, plugin.RootPackage)], i)
		_, _ = fmt.Fprintf(source, "\tif err != nil { return result, fmt.Errorf(%q, err) }\n", "decode config for plugin "+plugin.ID+": %w")
	}
	source.WriteString("\treturn result, nil\n}\n\n")
	source.WriteString(`func resolveConfigTable(tables map[string]map[string]any, id, name string) (map[string]any, error) {
	byID, hasID := tables[id]
	byName, hasName := tables[name]
	if hasID && hasName {
		return nil, fmt.Errorf("plugin %s (%s): present under both canonical id and short name", id, name)
	}
	if !hasID && !hasName {
		return nil, fmt.Errorf("plugin %s (%s): missing config table", id, name)
	}
	if hasID {
		return byID, nil
	}
	return byName, nil
}

func strictDecodeConfig[T any](table map[string]any) (T, error) {
	var value T
	encoded, err := toml.Marshal(table)
	if err != nil {
		return value, fmt.Errorf("encode plugin config table: %w", err)
	}
	decoder := toml.NewDecoder(bytes.NewReader(encoded))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&value); err != nil {
		return value, fmt.Errorf("decode plugin config: %w", err)
	}
	return value, nil
}

`)
}

func writeWiring(source *bytes.Buffer, lock *Lock, graph *Graph, aliases map[string]string) {
	componentNumber := map[*Component]int{}
	for i, component := range graph.Components {
		componentNumber[component] = i
	}
	pluginNumber := map[string]int{}
	for i, plugin := range lock.Plugins {
		pluginNumber[plugin.ID] = i
	}
	source.WriteString("func run(ctx context.Context, configPath, stateRoot string, process *processControl) error {\n")
	source.WriteString("\tconfigs, err := decodeConfigs(configPath)\n\tif err != nil { return err }\n\tcleanups := []ingotabi.Cleanup{}\n")
	for _, component := range graph.CreationOrder {
		number := componentNumber[component]
		alias := aliases[component.ImportPath]
		hasState := false
		for _, dependency := range component.DependencyList {
			if dependency.Host && dependency.HostType == "state" {
				hasState = true
				break
			}
		}
		if hasState {
			_, _ = fmt.Fprintf(source, "\tstateDir%d := filepath.Join(stateRoot, %q)\n", number, component.PluginID)
			_, _ = fmt.Fprintf(source, "\tif err := os.MkdirAll(stateDir%d, 0o700); err != nil { return cleanupAll(ctx, cleanups, err) }\n", number)
		}
		_, _ = fmt.Fprintf(source, "\tdeps%d := %s.Dependencies{\n", number, alias)
		for _, dependency := range component.DependencyList {
			if dependency.Host {
				switch dependency.HostType {
				case "state":
					_, _ = fmt.Fprintf(source, "\t\t%s: stateScope{dir: stateDir%d},\n", dependency.Name, number)
				default:
					_, _ = fmt.Fprintf(source, "\t\t%s: process,\n", dependency.Name)
				}
				continue
			}
			_, _ = fmt.Fprintf(source, "\t\t%s: %s,\n", dependency.Name, dependencyExpression(dependency, componentNumber, aliases))
		}
		source.WriteString("\t}\n")
		for _, dependency := range component.DependencyList {
			if dependency.Host {
				continue
			}
			path := component.ID + ".Dependencies." + dependency.Name
			if dependency.Cardinality == CardinalityMany {
				_, _ = fmt.Fprintf(source, "\tif err := validateCollection(reflect.ValueOf(deps%d.%s), %q, true); err != nil { return cleanupAll(ctx, cleanups, err) }\n", number, dependency.Name, path)
			} else {
				_, _ = fmt.Fprintf(source, "\tif err := validateRequired(reflect.ValueOf(deps%d.%s), %q); err != nil { return cleanupAll(ctx, cleanups, err) }\n", number, dependency.Name, path)
			}
		}
		_, _ = fmt.Fprintf(source, "\texports%d, cleanup%d, constructErr%d := %s.New(ctx, configs.Plugin%d, deps%d)\n", number, number, number, alias, pluginNumber[component.PluginID], number)
		_, _ = fmt.Fprintf(source, "\t_ = exports%d\n", number)
		_, _ = fmt.Fprintf(source, "\tif cleanup%d != nil { cleanups = append(cleanups, cleanup%d) }\n", number, number)
		_, _ = fmt.Fprintf(source, "\tif constructErr%d != nil { return cleanupAll(ctx, cleanups, fmt.Errorf(%q, constructErr%d)) }\n", number, "construct "+component.ID+": %w", number)
	}
	source.WriteString("\tif process.Mode() == invocation.ModeCheck { return cleanupAll(ctx, cleanups, nil) }\n")
	source.WriteString("\t<-ctx.Done()\n")
	// Snapshot shutdown causes only after cleanup. A normal request cancels
	// the graph immediately, but a concurrent fatal request arriving during
	// cleanup must still determine the final process result.
	source.WriteString("\tcleanupErr := cleanupAll(ctx, cleanups, nil)\n")
	source.WriteString("\treturn errors.Join(process.result(), cleanupErr)\n}\n")
}

func dependencyExpression(dependency *Dependency, componentNumber map[*Component]int, aliases map[string]string) string {
	typeString := func(value types.Type) string {
		return types.TypeString(value, func(pkg *types.Package) string {
			if alias, ok := aliases[pkg.Path()]; ok {
				return alias
			}
			return pkg.Name()
		})
	}
	sourceExpression := func(provider Provider) string {
		return fmt.Sprintf("exports%d.%s", componentNumber[provider.Component], provider.Export.Name)
	}
	switch dependency.Cardinality {
	case CardinalityOne:
		return sourceExpression(dependency.Providers[0])
	case CardinalityOptional:
		sdkAlias := aliases[dependency.WrapperRuntime]
		if len(dependency.Providers) == 0 {
			return fmt.Sprintf("%s.None[%s]()", sdkAlias, typeString(dependency.Target))
		}
		return fmt.Sprintf("%s.Some[%s](%s)", sdkAlias, typeString(dependency.Target), sourceExpression(dependency.Providers[0]))
	case CardinalityMany:
		var expression strings.Builder
		target := typeString(dependency.Target)
		_, _ = fmt.Fprintf(&expression, "func() []%s { values := make([]%s, 0)", target, target)
		for _, provider := range dependency.Providers {
			suffix := ""
			if provider.Flatten {
				suffix = "..."
			}
			_, _ = fmt.Fprintf(&expression, "; values = append(values, %s%s)", sourceExpression(provider), suffix)
		}
		expression.WriteString("; return values }()")
		return expression.String()
	default:
		panic("unknown cardinality " + dependency.Cardinality)
	}
}

func quote(value string) string { return strconv.Quote(value) }
